spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/test_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: 1234
server:
  servlet:
    session:
      setMaxInactiveInterval: 600
      timeout: 600
      tracking-modes: cookie