spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    clientname: jihyun
    url: jdbc:mysql://192.168.250.33:3306/nature?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: wlgus
server:
  servlet:
    session:
      setMaxInactiveInterval: 600
      timeout: 600
      tracking-modes: cookie